# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CartAGen4QGIS
                                 A QGIS plugin
 Cartographic generalization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""

__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2023-05-11'
__copyright__ = '(C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing, QgsFeatureSink, QgsProcessingAlgorithm,
    QgsFeature, QgsGeometry, QgsProcessingParameterDefinition, QgsWkbTypes
)
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink, 
    QgsProcessingAlgorithm,
    QgsFeature,
    QgsGeometry,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterFeatureSource, 
    QgsProcessingParameterFeatureSink, 
    QgsProcessingParameterNumber,
    QgsProcessingParameterDistance,
    QgsProcessingParameterEnum,
    QgsProcessingParameterBoolean,
    QgsProcessingException,
    QgsProcessingParameterMultipleLayers
)

class CatmullRomSmoothing(QgsProcessingAlgorithm):
    """
    Smooth a line or polygon and preserve vertexes.

    This algorithm was proposed by Catmull and Rom, this is the version proposed by Barry and Goldman 
    that makes use of the de Boor’s algorithm for evaluating spline curves in B-spline form.

    Catmull-Rom splines are a family of cubic interpolating splines that pass through all control points. 
    The alpha parameter controls the type of parameterization: 0 for uniform, 0.5 for centripetal (default), and 1 for chordal. 
    Centripetal parameterization avoids cusps and self-intersections.

    Parameters:
        line (LineString) – The line to smooth.

        subdivisions (int, optional) – Number of interpolated points between each pair of control points. Default is 10. Higher values produce smoother curves.

        alpha (float, optional) – Parameterization type. Default is 0.5 (centripetal):

            0.0: uniform parameterization

            0.5: centripetal parameterization (recommended, prevents loops)

            1.0: chordal parameterization

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    
    INPUT = 'INPUT'

    SUBDIVISIONS = 'SUBDIVISIONS'
    ALPHA = 'ALPHA'
 
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Catmull-Rom'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Lines'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(
            "Smooth a line or polygon and preserve vertexes. \n"\
            "This algorithm was proposed by Catmull and Rom, this is the version proposed by Barry and Goldman that makes use of the de Boor’s algorithm for evaluating spline curves in B-spline form. \n"\
            "Parameters : \n"\
            "- Subdivisions : Number of interpolated points between each pair of control points. Higher values produce smoother curves. \n"\
            "- Alpha : Parameterization type: \n  "\
            ". Uniform parameterization \n  "\
            ". Centripetal parameterization (recommended, prevents loops) \n  "\
            ". Chordal parameterization \n"\
            "Link to the doc : \n"\
            "https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_catmull_rom.html#cartagen.smooth_catmull_rom"
            )
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CatmullRomSmoothing()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input lines or polygons :'),
                [QgsProcessing.TypeVectorPolygon, QgsProcessing.TypeVectorLine]
            )
        )

        subdivisions = QgsProcessingParameterNumber(
            self.SUBDIVISIONS,
            self.tr('Subdivisions :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=10,
            optional=False
        )
        self.addParameter(subdivisions)

        listAlpha = ['Centrepital Parametrization','Uniform parametrization', 'Chordal parametrization']
        alpha = QgsProcessingParameterEnum(
            self.ALPHA,
            self.tr('Alpha :'),
            options = listAlpha,
            defaultValue = 'Centrepital Parametrization'
        )
        alpha.setFlags(alpha.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(alpha)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Catmull-Rom')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_catmull_rom
        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from shapely import Polygon
        from shapely.wkt import loads

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        # retrieve the other parameters values
        subdivisions = self.parameterAsInt(parameters, self.SUBDIVISIONS, context)
        alpha = self.parameterAsEnum(parameters, self.ALPHA, context)
        dico = {0:0.5, 1:0.0, 1:1}

        print(f"indice : {alpha} et alpha {dico[alpha]}")

        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        if source.wkbType().name == 'Polygon':
            print("Je suis un polygon")
            gs = gdf.copy()
            for i in range(len(gdf)):
                try:
                    gs.loc[i,'geometry'] = smooth_catmull_rom(list(gs.geometry)[i], alpha=dico[alpha], subdivisions=subdivisions)
                    print("Je suis dans try")
                except:
                    gs.loc[i,'geometry'] = gs.loc[i,'geometry']
                    print("Je suis dans except")
                
                #gs.loc[i,'geometry'] = Polygon(gs.loc[i,'geometry'])

            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        else:
            print("Je suis une ligne")
            gs = gdf.copy()
            print(gs)
            for i in range(len(gdf)):
                # print("Je suis dans la premiere boucle")
                geommultiple = gs.loc[i,'geometry']
                # print(geommultiple)
                listGeomSimple = list(geommultiple.geoms)
                listeTraitee = []
                # print(listGeomSimple)

                for ligne in listGeomSimple:
                    # print("Je suis dans la deuxième boucle.")
                    # print(ligne)
                    ligneTraitee = smooth_catmull_rom(ligne, alpha=dico[alpha], subdivisions=subdivisions)
                    listeTraitee.append(ligneTraitee)

                # print(listeTraitee)
                gs.loc[i,'geometry'] = listeTraitee
            
            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

            # Create the output sink    
            (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                    context, res[0].fields(), source.wkbType(), source.sourceCrs())
            
            # Add a feature in the sink
            sink.addFeatures(res, QgsFeatureSink.FastInsert)

            return {
                self.OUTPUT: dest_id
            }
    
class ChaikinSmoothing(QgsProcessingAlgorithm):
    """
    Smooth a line or polygon by cutting corners.

    This algorithm was proposed by Chaikin [1] and this version makes use of the equivalent multi-step algorithm introduced by Wu et al. .
    It is a simple subdivision scheme that repeatedly cuts corners of a line or polygon. Each iteration doubles the number of vertices 
    and produces a smoother curve that converges to a quadratic B-spline.

    Parameters:
        line (LineString) – The line to smooth.

        iterations (int, optional) – Number of subdivision iterations (k parameter). Default is 3. Each iteration doubles the number of vertices (2^k ITERATIONS per segment).

        keep_ends (bool, optional) – Whether to keep the original endpoints fixed for open lines. Default is True. For closed geometries, this parameter is ignored and corners are always cut.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    
    INPUT = 'INPUT'

    ITERATIONS = 'ITERATIONS'
    KEEP_ENDS = 'KEEP_ENDS'
 
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Chaikin'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Lines'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(
            "Smooth a line or polygon by cutting corners. \n"\
            "This algorithm was proposed by Chaikin and this version makes use of the equivalent multi-step algorithm introduced by Wu et al.\n"\
            "It is a simple subdivision scheme that repeatedly cuts corners of a line or polygon. Each iteration doubles the number of vertices and produces a smoother curve that converges to a quadratic B-spline. \n"\
            "Parameters : \n"\
            "- Iterations : Number of subdivision iterations (k parameter). Each iteration doubles the number of vertices (2^k subdivisions per segment). \n"\
            "- Keep ends : Whether to keep the original endpoints fixed for open lines. For closed geometries, this parameter is ignored and corners are always cut. \n"\
            "Link to the doc : \n"\
            "https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_chaikin.html#cartagen.smooth_chaikin"
            )
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ChaikinSmoothing()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input lines or polygons :'),
                [QgsProcessing.TypeVectorPolygon, QgsProcessing.TypeVectorLine]
            )
        )

        iterations = QgsProcessingParameterNumber(
            self.ITERATIONS,
            self.tr('Iterations :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=3,
            optional=False
        )
        self.addParameter(iterations)

        keep_ends = QgsProcessingParameterBoolean(
            self.KEEP_ENDS,
            self.tr('Keep ends ?'),
            defaultValue=True,
            optional=False
        )
        self.addParameter(keep_ends)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Chaikin')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_chaikin
        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from shapely import Polygon
        from shapely.wkt import loads

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        # retrieve the other parameters values
        iterations = self.parameterAsInt(parameters, self.ITERATIONS, context)
        keep_ends = self.parameterAsBoolean(parameters, self.KEEP_ENDS, context)

        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        if source.wkbType().name == 'Polygon':
            print("Je suis un polygon")
            gs = gdf.copy()
            for i in range(len(gdf)):
                #try:
                gs.loc[i,'geometry'] = smooth_chaikin(list(gs.geometry)[i], iterations=iterations, keep_ends=keep_ends)
                # except:
                #     gs.loc[i,'geometry'] = gs.loc[i,'geometry'] 
                
                #gs.loc[i,'geometry'] = Polygon(gs.loc[i,'geometry'])

            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        else:
            print("Je suis une ligne")
            gs = gdf.copy()
            print(gs)
            for i in range(len(gdf)):
                print("Je suis dans la premiere boucle")
                geommultiple = gs.loc[i,'geometry']
                print(geommultiple)
                listGeomSimple = list(geommultiple.geoms)
                listeTraitee = []
                print(listGeomSimple)

                for ligne in listGeomSimple:
                    print("Je suis dans la deuxième boucle.")
                    print(ligne)
                    ligneTraitee = smooth_chaikin(ligne, iterations=iterations, keep_ends=keep_ends)
                    listeTraitee.append(ligneTraitee)

                print(listeTraitee)
                gs.loc[i,'geometry'] = listeTraitee
                #     print("Je suis dans try")
                # except:
                #     gs.loc[i,'geometry'] = gs.loc[i,'geometry']
                #     print("Je suis dans except")
            
            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }
    
class GaussianSmoothing(QgsProcessingAlgorithm):
    """
    Smooth a line and attenuate its inflexion points.
    The gaussian smoothing has been studied by Babaud et al. for image processing,
    and by Plazanet for the generalisation of cartographic features.

    Parameters:
        line (LineString) – The line to smooth.

        sigma (float, optional) – Gaussian filter strength. Default value to 30, which is a high value.

        sample (float, optional) – The length in meter between each nodes after resampling the line. If not provided, the sample is derived from the line and is the average distance between each consecutive vertex.

        densify (bool, optional) – Whether the resulting line should keep the new node density. Default to True.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    SIGMA = 'SIGMA'
    SAMPLE = 'SAMPLE'
    DENSIFY = 'DENSIFY'
 
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Gaussian'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Lines'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr("Smooth a line and attenuate its inflexion points.\nThe gaussian smoothing has been studied by Babaud et al. for image processing, and by Plazanet for the generalisation of cartographic features. \n Accept Multi geometries. If a polygon is provided, it also apply the smoothing to its holes using the same parameters. \n Link to the doc : \n https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_gaussian.html#cartagen.smooth_gaussian")
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return GaussianSmoothing()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('The geometry to smooth. \n If a line is provided, the first and last vertexes are kept. If a polygon is provided, every vertex is smoothed.'),
                [QgsProcessing.TypeVectorPolygon, QgsProcessing.TypeVectorLine]
            )
        )


        sigma = QgsProcessingParameterNumber(
            self.SIGMA,
            self.tr('Gaussian filter strength. \n Default value to 30, which is a high value.'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=30.0,
            optional=False
        )
        self.addParameter(sigma)
       
        densify = QgsProcessingParameterBoolean(
            self.DENSIFY,
                self.tr('Densify. \n Whether the resulting geometry should keep the new vertex density.'),
                optional=False,
                defaultValue=True
            )
        densify.setFlags(densify.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(densify)

        sample = QgsProcessingParameterNumber(
            self.SAMPLE,
            self.tr('Length in meter between each nodes after resampling. \n If not provided, the sample is derived from the geometry and is the average distance between each consecutive vertex.'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=30.0,
            optional=False
        )
        self.addParameter(sample)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Gaussian')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_gaussian
        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from shapely import Polygon
        from shapely.wkt import loads

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        # retrieve the other parameters values
        sigma = self.parameterAsDouble(parameters, self.SIGMA, context)
        sample = self.parameterAsDouble(parameters, self.SAMPLE, context)
        densify = self.parameterAsBoolean(parameters, self.DENSIFY, context)

        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        if source.wkbType().name == 'Polygon':
            gs = gdf.copy()
            for i in range(len(gdf)):
                #try:
                gs.loc[i,'geometry'] = smooth_gaussian(list(gs.geometry)[i], sigma= sigma, sample= sample, densify = densify)
                # except:
                #     gs.loc[i,'geometry'] = gs.loc[i,'geometry'] 
                
                #gs.loc[i,'geometry'] = Polygon(gs.loc[i,'geometry'])

            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        else:
            gs = gdf.copy()
            for i in range(len(gdf)):
                try:
                    gs.loc[i,'geometry'] = smooth_gaussian(list(gs.geometry)[i], sigma= sigma, sample= sample, densify = densify)
                except:
                    gs.loc[i,'geometry'] = gs.loc[i,'geometry']
            
            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }
    