# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CartAGen4QGIS
                                 A QGIS plugin
 Cartographic generalization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""

__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2023-05-11'
__copyright__ = '(C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing, QgsFeatureSink, QgsProcessingAlgorithm,
    QgsFeature, QgsGeometry, QgsProcessingParameterDefinition
)
from qgis.core import (
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterNumber,
    QgsProcessingParameterEnum,
    QgsProcessingParameterString,
    QgsProcessingParameterDistance,
    QgsProcessingParameterMultipleLayers
)
class BuildingFER (QgsProcessingAlgorithm):

    """
    Regularize a polygon using feature edge reconstruction.

    This algorithm was proposed by Yang et al. FER enforces orthogonality and clean edge alignment on raw segmentation polygons. 
    It first estimates the dominant orientation of a building, then iteratively snaps near-parallel and near-perpendicular edges 
    to that principal axis, using Douglas-Peucker simplification, minimum-rotated-rectangle fitting, and a local reconstruction loop.

    This is slightly modified version of the SamGeo Python package available here. It is basically the same but without the osgeo 
    dependencies.

    Parameters:

            polygon (Polygon or MultiPolygon) – Input building footprint(s) to regularize.

            length (float) – Minimum edge length used during the reconstruction pass (default 6 m).

            area (float) – Polygons whose area is below this value (m²) are discarded (default 6 m²).

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    INPUT_BUILDING = "INPUT_BUILDING"
    OUTPUT_BUILDING="OUTPUT_BUILDING"
    LENGTH="LENGTH"
    AREA="AREA"

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Regularize Building FER'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())
    
    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Buildings'
    
    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())
    
    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(
            "/!\ Drop Z and M /!\ \n"\
            "Regularize a polygon using feature edge reconstruction.\n"\
            "This algorithm was proposed by Yang et al. FER enforces orthogonality and clean edge alignment on raw segmentation polygons. It first estimates the dominant orientation of a building, then iteratively snaps near-parallel and near-perpendicular edges to that principal axis, using Douglas-Peucker simplification, minimum-rotated-rectangle fitting, and a local reconstruction loop. \n "\
            "This is slightly modified version of the SamGeo Python package available here. It is basically the same but without the osgeo dependencies.\n"\
            "Parameters:\n"\
            "- Length : Minimum edge length used during the reconstruction pass (default 6 m).\n"\
            "- Area : Polygons whose area is below this value (m²) are discarded (default 6 m²).\n"\
            "Link to the doc :\n"\
            "https://cartagen.readthedocs.io/en/latest/reference/cartagen.regularize_building_fer.html#cartagen.regularize_building_fer"
            )

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def createInstance(self):
        return BuildingFER()
    
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        input = QgsProcessingParameterFeatureSource(
            name=self.INPUT_BUILDING,
            description=self.tr("Input building footprint(s) to regularize :"),
            types=[QgsProcessing.TypeVectorPolygon]
        )
        self.addParameter(input)

        length = QgsProcessingParameterNumber(
            name=self.LENGTH,
            description=self.tr("Length :"),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=6.0
        )
        self.addParameter(length)

        area = QgsProcessingParameterNumber(
            name=self.AREA,
            description=self.tr("Area :"),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=6.0
        )
        self.addParameter(area)

        output = QgsProcessingParameterFeatureSink(
            name=self.OUTPUT_BUILDING,
            description=self.tr("Regularized FER")
        )
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import regularize_building_fer
        from cartagen4qgis.src.tools import list_to_qgis_feature, list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT_BUILDING, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        # Retrieve the other parameter values 
        length = self.parameterAsDouble(parameters, self.LENGTH, context)
        area = self.parameterAsDouble(parameters, self.AREA, context)

        feedback.setProgress(1)

        #Preparing the data and process
        gs = gdf.copy()
        for i in range(len(gdf)):
            listBuil = []

            # print(f"Je suis dans la premiere boucle pour la {i}eme fois")
            batRegularizeFer = regularize_building_fer(gs['geometry'].loc[i], length=length, area=area)            
            listBuil.append(batRegularizeFer)

            gs.loc[i,'geometry'] = listBuil
        # print(f"Longueur avant traitement : {len(gs)}")

        feedback.setProgress(80)


        for row in gs.iterrows():
            # print(f"ligne :{row[1]['geometry']}")
            if row[1]['geometry']== None :
                # print(f"la geom {row[0]} est vide")
                gs = gs.drop(labels=row[0], axis='index')

        # print(f"Longueur après traitement : {len(gs)}")

        res = gs.to_dict(orient='records')
        # print(f"le dico {res} de type {type(res)}")
        # print(f"pb de keys : {len(res[0].keys())}")
        res = list_to_qgis_feature_2(res, source.fields())

        #Create the ouput sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT_BUILDING, context, 
            res[0].fields(), source.wkbType(), source.sourceCrs())
        # Add a feature in the sink
        print(sink)
        print(res[0].fields())
        print(parameters)
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT_BUILDING: dest_id
        }
    
class BuildingRectangle(QgsProcessingAlgorithm):
    """
    Transform a polygon into a rectangle.

    This function transforms a polygon to a rectangle using the minimum rotated rectangle and scale it up or down.

    Parameters:

        polygon (Polygon) – The polygon to regularize.

        factor (float, optional) – The scaling factor to apply.

        method (str, optional) –

        The method to calculate the rectangle:

            ’mbr’ calculate the minimum rotated bounding rectangle.

            ’mbtr’ calculate minimum rotated bounding touching rectangle. It is the same as the mbr but the rectangle and the polygon must have at least one side in common.

    """
    INPUT="INPUT"
    OUTPUT="OUTPUT"
    FACTOR="FACTOR"
    METHOD="METHOD"

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Regularize Building Rectangle'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())
    
    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Buildings'
    
    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())
    
    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(
            "Transform a polygon into a rectangle.\n"\
            "This function transforms a polygon to a rectangle using the minimum rotated rectangle and scale it up or down.\n"\
            "Parameters:\n"\
            "- Factor : The scaling factor to apply.\n"\
            "- Method : The method to calculate the rectangle: \n  "\
            ". 'mbr' calculate the minimum rotated bounding rectangle. \n  "\
            ". 'mbtr' calculate minimum rotated bounding touching rectangle. It is the same as the mbr but the rectangle and the polygon must have at least one side in common. \n"\
            "Link to the doc : \n"\
            "https://cartagen.readthedocs.io/en/latest/reference/cartagen.regularize_building_rectangle.html#cartagen.regularize_building_rectangle"
            )
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def createInstance(self):
        return BuildingRectangle()
    
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        input = QgsProcessingParameterFeatureSource(
            name=self.INPUT,
            description=self.tr("Input building footprint(s) to regularize :"),
            types=[QgsProcessing.TypeVectorPolygon]
        )
        self.addParameter(input)

        factor = QgsProcessingParameterNumber(
            name=self.FACTOR,
            description=self.tr("Factor :"),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1.0
        )
        self.addParameter(factor)

        listMethods = ['mbr', 'mbtr']
        method = QgsProcessingParameterEnum(
            name=self.METHOD,
            description=self.tr("Method :"),
            options=listMethods,
            defaultValue='mbr'
        )
        self.addParameter(method)

        output = QgsProcessingParameterFeatureSink(
            name=self.OUTPUT,
            description=self.tr("Regularized Rectangle")
        )
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        import geopandas as gpd
        import pandas
        from cartagen import regularize_building_rectangle
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        # Retrieve the other parameter values 
        factor = self.parameterAsDouble(parameters, self.FACTOR, context)
        method = self.parameterAsEnum(parameters, self.METHOD, context)
        print(type(method))
        dicoMethods = {0:'mbr', 1:'mbtr'}
        print(f"le numero {method} et la methode {dicoMethods[method]}")

        #Preparing the data and process
        gs = gdf.copy()
        for i in range(len(gdf)):
            # print(f"Je suis dans la premiere boucle pour la {i}eme fois.")
            geommultiple = gs['geometry'].loc[i]
            listGeomSimple = list(geommultiple.geoms)
            # print(f"liste des géométrie : {listGeomSimple}")
            listeTraitee = []

            for ligne in listGeomSimple:
                # print("Je suis dans la deuxième boucle.")
                # print(f"Le polyg qui va dans le traitement : {ligne}")
                ligneTraitee = regularize_building_rectangle(ligne, factor=factor, method=dicoMethods[method])
                # print(f"Le polyg après le traitement {ligneTraitee}")
                listeTraitee.append(ligneTraitee)
                # print(f"Le append a eu lieu. La liste est : {listeTraitee}")

            # print(f"La liste de geom qui va être affichée : {listeTraitee}")
            gs.loc[i,'geometry'] = listeTraitee

        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())
        print(f"Le dictionnaire : {res}")

        #Create the ouput sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context, 
            res[0].fields(), source.wkbType(), source.sourceCrs())
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }
    
class BuildingRegression(QgsProcessingAlgorithm):

    """
    Regularize a polygon using recursive linear regression.

    This algorithm was proposed by Bayer and used for remote sensing building regularization in Yang. It first defines the four sides of the polygon using an enclosing rectangle that has one side touching the side of the polygon. Then, every side is recursively subdivided until the standard deviation of the vertex composing the side is below the provided threshold. The standard deviation is calculated using the horizontal or vertical regression line which will output a squared polygon.

    Parameters:

        polygon (Polygon) – The polygon to regularize.

        Sigma (float) – The standard deviation threshold above which the recursion continues.

    """
    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    INPUT_BUILDING = "INPUT_BUILDING"
    OUTPUT_BUILDING="OUTPUT_BUILDING"
    SIGMA="SIGMA"

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Regularize Building Regression'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())
    
    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Buildings'
    
    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())
    
    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(
            "Regularize a polygon using recursive linear regression.\n"\
            "This algorithm was proposed by Bayer and used for remote sensing building regularization in Yang. It first defines the four sides of the polygon using an enclosing rectangle that has one side touching the side of the polygon. Then, every side is recursively subdivided until the standard deviation of the vertex composing the side is below the provided threshold. The standard deviation is calculated using the horizontal or vertical regression line which will output a squared polygon. \n"\
            "Parameters: \n"\
            "- Sigma : The standard deviation threshold above which the recursion continues. \n"\
            "Link to the doc : \n"\
            "https://cartagen.readthedocs.io/en/latest/reference/cartagen.regularize_building_regression.html#cartagen.regularize_building_regression "
            )
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def createInstance(self):
        return BuildingRegression()
    
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        input = QgsProcessingParameterFeatureSource(
            name=self.INPUT_BUILDING,
            description=self.tr("Input building footprint(s) to regularize :"),
            types=[QgsProcessing.TypeVectorPolygon]
        )
        self.addParameter(input)

        sigma = QgsProcessingParameterNumber(
            name=self.SIGMA,
            description=self.tr("Sigma  :"),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1.0
        )
        self.addParameter(sigma)

        output = QgsProcessingParameterFeatureSink(
            name=self.OUTPUT_BUILDING,
            description=self.tr("Regularized Regression")
        )
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        import geopandas as gpd
        import pandas
        from cartagen import regularize_building_regression
        from cartagen4qgis.src.tools import list_to_qgis_feature, list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT_BUILDING, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        # Retrieve the other parameter values 
        sigma = self.parameterAsDouble(parameters, self.SIGMA, context)

        #Preparing the data and process
        gs = gdf.copy()
        for i in range(len(gdf)):
            print(f"Je suis dans la premiere boucle pour la {i}eme fois.")
            geommultiple = gs['geometry'].loc[i]
            listGeomSimple = list(geommultiple.geoms)
            print(f"liste des géométrie : {listGeomSimple}")
            listeTraitee = []

            for ligne in listGeomSimple:
                print("Je suis dans la deuxième boucle.")
                print(f"Le polyg qui va dans le traitement : {ligne}")
                ligneTraitee = regularize_building_regression(ligne, sigma=sigma)
                print(f"Le polyg après le traitement {ligneTraitee}")
                listeTraitee.append(ligneTraitee)
                print(f"Le append a eu lieu. La liste est : {listeTraitee}")

            print(f"La liste de geom qui va être affichée : {listeTraitee}")
            gs.loc[i,'geometry'] = listeTraitee

        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())
        print(f"Le dictionnaire : {res}")

        #Create the ouput sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT_BUILDING, context, 
            res[0].fields(), source.wkbType(), source.sourceCrs())
        # Add a feature in the sink
        print(sink)
        print(res[0].fields())
        print(parameters)
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT_BUILDING: dest_id
        }
